# Common NFS Volume
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nas
spec:
  capacity:
    storage: 1024Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: pi0
    path: "/nas"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1024Gi