defaultEntryPoints = ["http","https"]
debug = true
logLevel = "DEBUG"

#Config to redirect http to https
[entryPoints]
  [entryPoints.http]
    address = ":80"
    compress = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
    address = ":443"
    compress = true
    [entryPoints.https.tls]
      [[entryPoints.https.tls.certificates]]
      certFile = "/certs/com.allandequeiroz.pem"
      keyFile = "/certs/com.allandequeiroz.key"

[api]
  [api.statistics]
    recentErrors = 10
    debug = true

[kubernetes]
  labelselector = "traffic-type=external"

[metrics]
  [metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]
  entryPoint = "traefik"

[ping]
entryPoint = "http"

[accessLog]

#[consul]
#  endpoint = "consul-traefik-consul.kube-system.svc:8500"
#  watch = true
#  prefix = "traefik-external"
#
#[acme]
#  email = "allandequeiroz@gmail.com"
#  storage = "traefik-external-certificates/acme/account"
#  acmeLogging = true
#  entryPoint = "https"
#  OnHostRule = true
#  [acme.httpChallenge]
#    entryPoint="http"
