defaultEntryPoints = ["http","https"]
debug = false
logLevel = "INFO"

# Do not verify backend certificates (use https backends)
InsecureSkipVerify = true

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[api]
  [api.statistics]
    recentErrors = 10
    debug = true

#Config to redirect http to https
#[entryPoints]
#  [entryPoints.http]
#  address = ":80"
#  compress = true
#    [entryPoints.http.redirect]
#    entryPoint = "https"
#  [entryPoints.https]
#  address = ":443"
#    [entryPoints.https.tls]

#[web]
#  address = ":8080"

[kubernetes]
  labelselector = "traffic-type=internal"

[metrics]
  [metrics.prometheus]
  buckets=[0.1,0.3,1.2,5.0]
  entryPoint = "traefik"

[ping]
entryPoint = "http"
