version: '3.6'

services:
  ddns:
    restart: always
    image: allandequeiroz/cloudflare-ddns:arm
    volumes:
      - /nas/home-stack/1-ddns_cloudflare/bin/cloudflare_ddns.py:/root/ddns/cloudflare_ddns.py
      - /nas/home-stack/1-ddns_cloudflare/bin/root:/var/spool/cron/crontabs/root
    env_file:
      - /nas/home-stack/99-misc/cloudflare_ddns.env
  
  nginx:
    restart: always
    image: allandequeiroz/nginx:latest
    ports: # Is host the best option?
      - mode: host
        target: 80
        published: 80
      - mode: host
        target: 443
        published: 443

  ghost:
    restart: always
    image: allandequeiroz/ghost-the-shell:arm
    ports:
      - mode: host
        target: 2368
        published: 2368
    volumes:
      - /nas/home-stack/6-ghost/conf/config.production.json:/var/www/ghost/config.production.json
      - /nas/home-stack/6-ghost/bin/start-ghost.sh:/root/start-ghost.sh
      - /nas/data/blog:/var/www/ghost/content/data/