version: '3.6'

services:
  ddns:
    image: allandequeiroz/cloudflare-ddns:arm64
    configs:
      - source: ddns_script
        target: /root/ddns/cloudflare_ddns.py
      - source: ddns_cron
        target: /var/spool/cron/crontabs/root
    env_file:
      - /nas/home-stack/99-misc/cloudflare_ddns.env
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
  
  nginx:
    image: allandequeiroz/nginx:latest
    ports: # Is host the best option?
      - mode: host
        target: 80
        published: 80
      - mode: host
        target: 443
        published: 443
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
      placement:
        constraints: 
          - node.hostname==glassfish

  ghost:
    image: allandequeiroz/ghost-the-shell:arm64
    ports:
      - mode: host
        target: 2368
        published: 2368
    configs:
      - source: ghost_config
        target: /var/www/ghost/config.production.json
      - source: ghost_starter
        target: /root/start-ghost.sh
    volumes:
      - /nas/data/blog:/var/www/ghost/content/data/
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 512M
      placement:
        constraints: 
          - node.hostname==glassfish

networks:
  swarm-home-stack:
configs:
  ddns_script:
    file: /nas/home-stack/1-ddns_cloudflare/bin/cloudflare_ddns.py
    name: ddns_script
  ddns_cron:
    file: /nas/home-stack/1-ddns_cloudflare/bin/root
    name: ddns_cron
  ghost_config:
    file: /nas/home-stack/6-ghost/conf/config.production.json
    name: ghost_conf
  ghost_starter:
    file: /nas/home-stack/6-ghost/bin/start-ghost.sh

