# MetalLb configuration
apiVersion: v1
kind: ConfigMap
metadata:
  namespace: metallb-system
  name: config
data:
  config: |
    address-pools:
    - name: home-stack
      protocol: layer2
      avoid-buggy-ips: true
      addresses:
      - 192.168.1.200-192.168.1.250
