#!/usr/bin/env bash

clear

kubectl delete -f traefik-external.yaml > /dev/null
kubectl delete -f traefik-internal.yaml > /dev/null

kubectl apply -f traefik-external.yaml > /dev/null
kubectl apply -f traefik-internal.yaml > /dev/null

sleep 5

echo -e "# SVC"
kubectl -n kube-system get svc -o wide | grep traefik
echo -e "\n# PO"
kubectl -n kube-system get po -o wide | grep traefik
echo -e "\n# ING"
kubectl -n kube-system get ing -o wide | grep traefik
echo -e "\n"